config/routes.rb
Rails.application.routes.draw do
  root 'messages#index'
  resources :messages
end

app/models/message.rb
class Message < ActiveRecord::Base
  validates :author, presence: true
  validates :content, presence: true
  validates :owner, presence: true

  validates :email,
            presence: true,
            format: {
              with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
            }

  def author_profile_image_url
    email_address = email.downcase
    hash = Digest::MD5.hexdigest(email_address)

    "http://www.gravatar.com/avatar/#{hash}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :set_tracking_cookie
  def set_tracking_cookie
    cookies.permanent[:jg_author] = SecureRandom.hex unless cookies.permanent[:jg_author]
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @messages = Message.all.order 'created_at desc'
  end

  def new
    @message = Message.new
  end

  def create
    @message = Message.new message_params
    @message.owner = cookies.permanent[:jg_author]

    if @message.save
      redirect_to :root, notice: 'Your message has been added!'
    else
      render :edit
    end
  end

  def edit
    @message = Message.find params[:id]
  end

  def update
    @message = Message.find params[:id]

    if @message.update_attributes message_params
      redirect_to :root, notice: 'Your message has been updated!'
    else
      render :edit
    end
  end

  def destroy
    @message = Message.find params[:id]

    if @message.destroy
      redirect_to :root, notice: 'Your message was successfully deleted'
    else
      redirect_to :root,
                  notice: 'An error occurred and you message was not deleted. Please try again.'
    end
  end

  private

  def message_params
    params.require(:message).permit(
      :author,
      :email,
      :content
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<!-- <title>Jaime's Guestbook</title> -->
		<title>Congratulations, Jaime!</title>

		<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
		<link href='http://fonts.googleapis.com/css?family=Pacifico|Open+Sans:300italic,400,700' rel='stylesheet' type='text/css'>
		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

		<%= csrf_meta_tags %>
	</head>
	<body>

		<%= render 'modules/flashes' %>

		<% if current_page?(controller: 'messages', action: 'index') %>
			<%= render 'modules/header' %>
		<% end %>

		<div id="main" class="container">
			<%= yield %>
		</div>

	</body>
</html>

app/views/messages/_form.html.erb
<%= form_for @message do |f| %>
	<fieldset class="card">
		<div class="field">
			<%= f.label :author, 'Your Name' %>
			<%= f.text_field :author %>

			<% if @message.errors[:author].any? %>
				<span class="help-text error"><%= @message.errors[:author][0] %></span>
			<% end %>
		</div>
		<div class="field">
			<%= f.label :email, 'Email' %>
			<%= f.email_field :email %>

			<% if @message.errors[:email].any? %>
				<span class="help-text error"><%= @message.errors[:email][0] %></span>
			<% end %>
		</div>
		<div class="field">
			<%= f.label :content, 'What would you like to say?' %>
			<%= f.text_area :content, class: 'redactor' %>

			<% if @message.errors[:content].any? %>
				<span class="help-text error"><%= @message.errors[:content][0] %></span>
			<% end %>
		</div>
		<div class="field actions">
			<%= link_to 'Cancel', root_path, class: 'button cancel' %>
			<%= f.submit 'Submit', class: 'commit' %>
		</div>
	</fieldset>
<% end %>

app/views/messages/edit.html.erb
<header>
	<h1>Edit Message</h1>
</header>

<%= render 'form' %>

app/views/messages/index.html.erb
<div>
	<%= link_to 'Leave Jaime a message', new_message_path, class: 'button' %>
</div>

<ul class="message-list">
	<% @messages.each do |message| %>
		<li class="card">
			<div class="author">
				<img src="<%= message.author_profile_image_url %>" alt="<%= message.author %>">
				<p><strong><%= message.author %></strong>, <%= message.created_at.strftime("%B %-d, %Y") %></p>
			</div>
			<p><%= simple_format message.content %></p>
			<% if message.owner == cookies.permanent[:jg_author] %>
				<div class="actions">
					<%= link_to 'Edit', edit_message_path(message), class: 'button' %>
					<%= link_to 'Delete', message_path(message), method: :delete, class: 'button destroy' %>
				</div>
			<% end %>
		</li>
	<% end %>
</ul>

app/views/messages/new.html.erb
<header>
	<h1>Create a new message</h1>
</header>

<%= render 'form' %>

app/views/modules/_flashes.html.erb
<% if flash.present? %>
	<div id="flash">
		<% flash.each do |key, value| -%>
			<%= javascript_tag do %>
				new window.App.Notification({
					message: "<%=j value %>",
					autoclose: true
				});
			<% end %>

			<noscript>
				<div class="flash-message flash-<%= key %>">
					<span><%= value.html_safe %></span>
				</div>
			</noscript>
		<% end -%>
	</div>
<% end %>

app/views/modules/_header.html.erb
<header class="main">
	<div class="container">
		<div class="content">
			<h1 class="display animated fadeInUp">Congratulations, Jaime!</h1>
			<p class="animated fadeInUp">We're all so proud of what you've accomplished so far, and we are looking forward to what the future holds for you.</p>
		</div>
	</div>

	<div class="scroll-down animated bounce">
		<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="40" height="40" viewBox="0 0 20 20" data-tags="chevron-down"><g fill="#ffffff" transform="scale(0.01953125 0.01953125)"><path d="M231.219 386.458c22.323-22.835 53.402-24.627 80.691 0l200.090 191.846 200.090-191.846c27.29-24.627 58.419-22.835 80.589 0 22.323 22.784 20.89 61.286 0 82.688-20.787 21.402-240.384 230.502-240.384 230.502-11.11 11.418-25.702 17.152-40.294 17.152s-29.184-5.734-40.397-17.152c0 0-219.494-209.101-240.384-230.502-20.941-21.402-22.323-59.904 0-82.688z"/></g><wappalyzerData id="wappalyzerData" style="display: none"/><script id="wappalyzerEnvDetection" src="chrome-extension://gppongmhjkpfnbhagpmjfkannfbllamg/js/inject.js"/></svg>
	</div>

</header>